baseurl = "https://loksh.in"
languageCode = "en-us"
title = "David Lokshin"
theme = "hugo-tania"
paginate = 6

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "🧐"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  enableFootnotes = true

  siteName = "Loksh.in"
  siteDesc = "My families stories on living under communism"
  author = "David Lokshin"

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = ""
    facebook = ""
    github = ""
    instagram = ""
    linkedin = ""
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = ""
    twitch = ""
    whatsapp = ""

  # Comments settigns
  [params.comments]
    enabled = false
    provider = "disqus"

[menu]
[[menu.header]]
  name = "Communism"
  url = "/articles/"

[markup]
[markup.highlight]
  noClasses = false
  lineNos = true
[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
